curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @1.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @2.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @3.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @4.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @5.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @6.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @7.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @8.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @9.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @10.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @11.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @12.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @13.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @14.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @15.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @16.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @17.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @18.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @19.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @20.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @21.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @22.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @23.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @24.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @25.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @26.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @27.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @28.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @29.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @30.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @31.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @32.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @33.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @34.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @35.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @36.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @37.0.json
curl -X POST "localhost:9200//_bulk" -H 'Content-Type: application/json' --data-binary @38.0.json